---
vm_flavor_options:
  small: n1-standard-1
  medium: n1-standard-2
  large: n1-standard-4

gcp_vm_os_images:
  centos-8: 'projects/centos-cloud/global/images/family/centos-8'
  centos-7: 'projects/centos-cloud/global/images/family/centos-7'
